# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('Icons', 'Icons'),
        ('ProgramImages', 'ProgramImages'),
        ('data', 'data'),  
    ],
    hiddenimports=[
        'subprocess',
        're',
        'requests',
        'json',
        'datetime',
        'PyQt6.QtCore',
        'PyQt6.QtWidgets',
        'PyQt6.QtGui',
        'sqlite3',
        'custom_dialogs',
        'download_manager',
        'downloads_manager',
        'downloads_tab',
        'drivers_tab',
        'gpu_detector',
        'image_helper',
        'json_data_manager',
        'loading_widget',
        'main_window',
        'news_tab',
        'programs_tab',
        'resource_path',
        'scroll_helper',
        'splash_screen',
        'temp_manager',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='UTILHELP',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,  
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['Icons\\utilhelp.ico'],
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,  # Отключаем UPX
    upx_exclude=[],
    name='UTILHELP',
)
